In [1]:
import numpy as np

### 0D Tensor / Scalar

In [2]:
a = np.array(5)

In [3]:
a

array(5)

In [4]:
a.ndim

0

### 1D Tensor / Vector

In [5]:
  arr = np.array([1,2,3])

In [6]:
arr

array([1, 2, 3])

In [7]:
arr.ndim

1

### 2D Tensor / Matrices

In [8]:
 mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
mat.ndim

2

### 3D Tensor

In [13]:
three_d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]]
              )

In [14]:
three_d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
three_d.ndim

3